require './calendar_watcher'
require './electronics_manager'

namespace :calendar do
  desc "fetch calendar and add events to queue"
  task :fetch do
    CalendarWatcher.new.run
  end
end

namespace :manager do
  desc 'start manager'
  task :start do
    ElectronicsManager.new.start
  end
end
